import React from 'react';
import { Mic } from 'lucide-react';
import type { Club, Fixture } from '../../types';
import { ClubCrest } from '../ui/ui';

/**
 * Post-match press conference: the managerial quotes and narrative headline
 * generated by the backend (matchreport.GeneratePressConference). Rendered on
 * the post-match Overview tab.
 */
export const PressConference: React.FC<{
  fixture: Fixture;
  home: Club | null;
  away: Club | null;
}> = ({ fixture, home, away }) => {
  const press = fixture.press_conference;
  if (!press || (!press.home_quote && !press.away_quote && !press.headline)) return null;

  const rows: Array<{ club: Club | null; manager: string; quote: string; side: 'home' | 'away' }> = [];
  if (press.home_quote) {
    rows.push({ club: home, manager: press.home_manager || '', quote: press.home_quote, side: 'home' });
  }
  if (press.away_quote) {
    rows.push({ club: away, manager: press.away_manager || '', quote: press.away_quote, side: 'away' });
  }

  return (
    <section className="console-card p-4 sm:p-5" data-press-conference="true">
      <div className="flex items-center justify-between gap-3">
        <p className="match-section-title">Press conference</p>
        <span className="flex items-center gap-1 text-[10px] uppercase tracking-[0.12em] text-sage">
          <Mic size={12} aria-hidden="true" /> Full-time
        </span>
      </div>
      {press.headline && (
        <p className="mt-3 border-l-2 border-brass/50 pl-3 text-[14px] font-semibold leading-relaxed text-bone">
          {press.headline}
        </p>
      )}
      {press.narrative && <p className="mt-2 text-[12px] leading-relaxed text-sage">{press.narrative}</p>}
      {rows.length > 0 && (
        <div className="mt-3 grid grid-cols-1 gap-3 md:grid-cols-2">
          {rows.map((row) => (
            <figure key={row.side} className="rounded-md border border-line bg-black/20 p-3">
              <figcaption className="flex items-center gap-2">
                <ClubCrest club={row.club} size={18} />
                <span className="text-[11px] font-bold uppercase tracking-[0.1em] text-bone">
                  {row.manager || row.club?.short_name || (row.side === 'home' ? 'Home' : 'Away')}
                </span>
              </figcaption>
              <blockquote className="mt-2 text-[12px] italic leading-relaxed text-bone/90">
                &ldquo;{row.quote}&rdquo;
              </blockquote>
            </figure>
          ))}
        </div>
      )}
    </section>
  );
};
